smoke_test added

diff --git a/.github/workflows/continues_testing.yml b/.github/workflows/continues_testing.yml
--- a/.github/workflows/continues_testing.yml
+++ b/.github/workflows/continues_testing.yml
@@ -5,10 +5,10 @@ name: Continuous Testing
 # Controls when the workflow will run
 on:
   # Triggers the workflow on push or pull request events but only for the "contact" branch
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+  #push:
+  #  branches: [ "main" ]
+  #pull_request:
+  #  branches: [ "main" ]
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
@@ -16,6 +16,7 @@ on:
 jobs:
   # This workflow contains a single job called "build"
   build:
+    timeout-minutes: 60
     # The type of runner that the job will run on
     name: choose VM
     runs-on: ubuntu-latest
@@ -29,3 +30,42 @@ jobs:
       # To get your Ubuntu version from the terminal
       - name: Ubuntu version
         run: lsb_release -a
+
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - name: Checkout repository
+        uses: actions/checkout@v7
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: lts/*
+
+      - name: Node version
+        run: "node --version"
+
+      - name: Install dependencies
+        run: "npm install"
+
+      - name: Install Playwright Browsers
+        run: npx playwright install --with-deps
+
+      # Run tests and save logs
+      - name: Run Playwright tests
+        run: npx playwright test | tee test-log.txt
+        continue-on-error: true
+
+      - name: Check for Failure
+        run: |
+          if grep -q "failed" test-log.txt; then
+            echo "***Tests failed***"
+            exit 1
+          fi
+
+      # Files saved as artifacts are stored on the server and available for download for 2 days
+      - name: Run Playwright tests
+        uses: actions/upload-artifact@v4
+        if: ${{ !cancelled() }}
+        with:
+          name: playwright-report
+          path: playwright-report/
+          retention-days: 2
